# -*- coding: utf-8 -*-
# Copyright 2018 Elitumdevelop S.A, Ing. Mario Rangel
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

{
    'name': "Módulo de Contabilidad",
    'summary': "Contabilidad.",
    'author': "Ing. Mario Rangel, Elitumgroup S.A",
    'website': "http://www.elitumgroup.com",
    'category': "Personalization",
    'license': "LGPL-3",
    'version': "1.0",
    'depends': [
        'account',
        'base_iban',
        'base_setup',
        'eliterp_management',
        'account_accountant',
        'sale',
        'stock',
        'payment',
        'purchase'
    ],
    'data': [
        'data/accounts.xml',
        'data/taxs.xml',
        'data/account_chart_template.yml',
        'data/sequences.xml',
        'security/ir.model.access.csv',
        'data/eliterp.tax.support.csv',
        'data/eliterp.way.pay.csv',
        'data/eliterp.type.document.csv',
        'views/accounting_views.xml',
        'views/sri_views.xml',
        'views/account_period_views.xml',
        'views/partner_views.xml',
        'views/invoice_views.xml',
        'views/check_views.xml',
        'views/payment_views.xml',
        'views/credit_debit_notes_views.xml',
        'views/bank_reconciliation_views.xml',
        'reports/accounting_reports.xml',
        'reports/reports_views.xml',
        'views/menus.xml',
        'views/dashboard.xml',
    ],
    'init_xml': [],
    'update_xml': [],
    'installable': True,
    'active': False,
}
